import Image from "next/image";

export default function Home() {
  return (
    <div>
      <div className="flex flex-col">
        <div className="flex flex-row justify-evenly">
          <div className="flex flex-col w-1/2 justify-center p-20">
            <h1 className="font-medium font-mainFont text-4xl mb-10 h-10 mt-20">
              What is ChainCloud ?
            </h1>
            <p className="font-medium">
              ChainCloud is a decentralized data storage solution built on a
              blockchain network. It offers a secure and reliable method of
              storing data, utilizing the inherent advantages of blockchain
              technology compared to traditional centralized storage systems.
            </p>
          </div>
          <div className="flex justify-center w-1/2">
            <img
              src="/blockchain_1.gif"
              width={500}
              height={500}
              alt="img"
              className="rounded-xl mt-20"
            ></img>
          </div>
        </div>

        <div className="flex flex-row justify-evenly mt-20">
          <div className="flex justify-center items-center w-1/2 ht-300">
            <img
              src="/blockchain_2.gif"
              alt="img"
              className="rounded-xl mt-20 h-1/2"
            ></img>
          </div>

          <div className="flex flex-col w-1/2 justify-center p-20">
            <h1 className="font-medium font-mainFont text-4xl mb-10 h-10 mt-20">
              Functions Of ChainCloud
            </h1>
            <ul className="font-medium">
              <li className="mb-4">
                <span className=" text-violet-600">Upload Data:</span> Users can
                upload any data to the blockchain using the contract.
              </li>
              <li className="mb-4">
                <span className="text-violet-600">IPFS Storage:</span> The
                contract stores the data to IPFS, which is a decentralized file
                storage system.
              </li>
              <li className="mb-4">
                <span className="text-violet-600">Pinning Service:</span>
                Pinata is used as a pinning service to ensure the availability
                and persistence of the IPFS data.
              </li>
              <li className="mb-4">
                <span className="text-violet-600">Store URI:</span> The contract
                stores the URI generated by Pinata to the blockchain, providing
                a reference to the uploaded data.
              </li>
              <li className="mb-4">
                <span className="text-violet-600">Grant Permission:</span>
                Users can grant permission to access their data by providing the
                address of the recipient.
              </li>
              <li className="mb-4">
                <span className="text-violet-600">Revoke Permission:</span>
                Users have the ability to revoke permission for any other user
                to access their data.
              </li>
              <li className="mb-4">
                <span className="text-violet-600">View Permissions:</span>
                Users can see a list of users who have been granted permission
                to access their data.
              </li>
              <li className="mb-4">
                <span className="text-violet-600">Retrieve Data:</span> Users
                and other authorized users can retrieve the data from the
                blockchain, using the stored URI as a reference.
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
